stages:
  - build
  - deploy

# Development environment
build_dev:
  stage: build
  tags:
    - development
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
  script:
    - exit 1
    # - echo "BUILDING IMAGE"
    # - docker build -t $IMAGE_NAME:latest .
    # - docker push $IMAGE_NAME:latest

deploy_dev:
  stage: deploy
  tags:
    - development
  needs:
    - build_dev
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
  script:
    - echo "deployed"
    # - kubectl set image deployment/dev-deployment dev-container=$IMAGE_NAME:latest --namespace=dev
    # - kubectl scale deployment dev-deployment --replicas=1 --namespace=dev
