stages:
  - build
  - deploy

# Development environment
build-dev:
  stage: build
  tags:
    - development 
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
  script:
    - docker build -t pimenvibritania/sre-example:dev-$CI_COMMIT_SHORT_SHA -t pimenvibritania/sre-example:latest .
    - docker push pimenvibritania/sre-example:dev-$CI_COMMIT_SHORT_SHA
    - docker push pimenvibritania/sre-example:latest

deploy-dev:
  stage: deploy
  tags:
    - development
  needs:
    - build-dev
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
  script:
    - export NAMESPACE_SRE=sre-application
    - echo $NAMESPACE_SRE
    - gcloud container clusters get-credentials development-cluster --zone asia-southeast2-a --project sre-development-2613
    - echo "Updating K8S Secret"
    - kubectl -n $NAMESPACE_SRE delete secret $NAMESPACE_SRE-app-secret || true
    - echo "Waiting to delete secret..."
    - sleep 5
    - kubectl -n $NAMESPACE_SRE create secret generic $NAMESPACE_SRE-app-secret --from-literal=host=$DB_HOST_DEV --from-literal=password=$DB_PASSWORD_DEV --from-literal=username=$DB_USERNAME --from-literal=database=$DB_NAME --from-literal=port=$DB_PORT 
    - kubectl -n $NAMESPACE_SRE set image deployment/$NAMESPACE_SRE-app-deployment $NAMESPACE_SRE-app=pimenvibritania/sre-example:latest
    - kubectl -n $NAMESPACE_SRE rollout restart deployment/$NAMESPACE_SRE-app-deployment

migration-dev:
  stage: deploy
  tags:
    - development
  needs:
    - deploy-dev
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
  script:
    - export NAMESPACE_SRE=sre-application
    - echo $NAMESPACE_SRE
    - gcloud container clusters get-credentials development-cluster --zone asia-southeast2-a --project sre-development-2613
    - kubectl -n $NAMESPACE_SRE delete job $NAMESPACE_SRE-db-migration || true
    - kubectl -n $NAMESPACE_SRE create job --from=cronjob.batch/$NAMESPACE_SRE-db-migration $NAMESPACE_SRE-db-migration || true
    - kubectl -n $NAMESPACE_SRE wait --for=condition=complete --timeout=120s job/$NAMESPACE_SRE-db-migration
